DROP TABLE IF EXISTS shopping_cart;
DROP TABLE IF EXISTS order_dishes;
DROP TABLE IF EXISTS `order` ;

DROP TABLE IF EXISTS category_dish;
DROP TABLE IF EXISTS dish ;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS user;
